#ifndef TTFY_TABEL_NAMES_H
#define TTFY_TABEL_NAMES_H

typedef enum
{
    TTFY_TABLE_NAME_None,
    TTFY_TABLE_NAME_HEAD,
    TTFY_TABLE_NAME_HHEA,
    TTFY_TABLE_NAME_MAXP
} TTFY_TableNameEnum;

#endif
